# Generated by Django 5.2.16 on 2026-07-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='users.salonmanager'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='salonimage',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('salon', 'weekday')},
        ),
    ]
