# Generated by Django 5.2.16 on 2026-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
