# Generated by Django 5.2.16 on 2026-07-10 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BREAK', 'Break'), ('LEAVE', 'Leave')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Employee Availabilities',
                'db_table': 'employee_availabilities',
            },
        ),
    ]
